name: unit-tests
on:
  push:
    paths: [
      '.github/workflows/unit-test.yaml',
      'litepipe/**'
    ]
jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
        cache: 'pip' # caching pip dependencies
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run unit tests
      run: |
        coverage run -m pytest litepipe/tests
